### ISSUE TITLE
No examples on setting custom timeouts on Load Balancers

### ISSUE THREAD

**Issue by chanster** [ibm-cloud-docs/loadbalancer-service#12]
Document [Advanced traffic management with IBM Cloud Load Balancer](https://cloud.ibm.com/docs/loadbalancer-service?topic=loadbalancer-service-advanced-traffic-management-with-ibm-cloud-load-balancer) states you can customize the **Client-side idle connection** and **Server-side idle connection** but does not show any examples or what to do to set this.

Please provide `ibmcloud cli` and/or Web Console screenshots on where to go to set this. We are unable to locate this setting anywhere.

**Comment by austinmama** [comment]
@jbmitch
