### ISSUE TITLE
LBaas Doc does not reflect reality - LBaaS support TLS 1.2 AND TLS 1.3

### ISSUE THREAD

**Issue by patmc2go** [ibm-cloud-docs/loadbalancer-service#13]
Two pages need updated: 
1. https://cloud.ibm.com/docs/loadbalancer-service?topic=loadbalancer-service-ssl-offload-with-ibm-cloud-load-balancer
2. https://cloud.ibm.com/docs/loadbalancer-service?topic=loadbalancer-service-choosing-a-preferred-cipher-suite-for-your-https-application

Re: 1
- Only the TLS 1.2 ciphers are listed
- The TLS 1.3 ciphers should be listed as they exist - an [SSL Labs test](https://www.ssllabs.com/ssltest/analyze.html?d=cloud%2dload%2dbalancer%2d1873809%2ddal10.clb.appdomain.cloud&hideResults=on&ignoreMismatch=on&latest) will tell you as much. 

Re: 2
- The missing TLS 1.3 ciphers need addressed here once the UI shows them
- There is a bug or odd behavior here that should be documented - if you deselect ALL the ciphers the UI will fail to save the update; no warning is given, no error shown; can't remember if the prior selection set is returned, or all get selected again by default.  

Pain point:  the cipher list shown in the UI does not match the cipher names shown by tools such as SSL Labs host tester.  
Life would be easier if they matched:
![image](https://user-images.githubusercontent.com/12019963/122461278-21384a00-cf81-11eb-9ca5-db239d118deb.png)

**Comment by jbmitch** [comment]
Sent to Anthony Pirri, for development input

**Comment by austinmama** [comment]
@jbmitch any update?

**Comment by austinmama** [comment]
@jbmitch Please provide status and close.

**Comment by jbmitch** [comment]
Resent to Anthony Perri for dev input.

**Comment by austinmama** [comment]
@jbmitch Please post in Slack channel.

**Comment by jbmitch** [comment]
Per Arda, this is up to date and the above issue can be closed.
