### ISSUE TITLE
Page is outdated. Monitoring has been replaced with Sysdig Monitor.

### ISSUE THREAD

**Issue by jjriv** [ibm-cloud-docs/loadbalancer-service#14]
The instructions on this page are outdated. There is no longer a Monitoring link in the left column of the Cloud Load Balancer pages. There is now a button to "Launch monitoring" which opens a new tab and takes you to Sysdig Monitor. 

When this page is updated it would also be helpful to include instructions on how to set up the dashboards in Sysdig Monitor. The ones we set up have gone missing, so it would be nice to have some official documentation to make sure we are setting them up as intended.

**Comment by jbmitch** [comment]
Sent to Anthony Pirri, for development input

**Comment by arjunsha** [comment]
The docs are pulished here: https://test.cloud.ibm.com/docs/loadbalancer-service?topic=loadbalancer-service-monitoring-and-managing-your-service

**Comment by austinmama** [comment]
@jbmitch Any updates?
