### ISSUE TITLE
Statement about data logging integration update  for LBaas listed for several months

### ISSUE THREAD

**Issue by notras** [ibm-cloud-docs/loadbalancer-service#17]
https://cloud.ibm.com/docs/loadbalancer-service?topic=loadbalancer-service-data-logging#viewing-logs-in-the-ibm-cloud-logging-analysis-service

"Data logging integration is currently being upgraded, and you will not be able to see your logs until this process completes. Please open a [support case](https://cloud.ibm.com/docs/loadbalancer-service?topic=loadbalancer-service-getting-help-and-support-for-ibm-cloud-load-balancer) for more information on this issue."

4 month ago Archana  promised to remove or update documentation: https://ibm-cloudplatform.slack.com/archives/C4YHGMBC7/p1661447481195029?thread_ts=1661242008.182689&cid=C4YHGMBC7 but statement still in the docs.

**Comment by jbmitch** [comment]
Fixed
