### ISSUE TITLE
Chinese document content is old and URL is invalid

### ISSUE THREAD

**Issue by liwang2017** [ibm-cloud-docs/loadbalancer-service#7]
In EN document https://cloud.ibm.com/docs/loadbalancer-service?topic=loadbalancer-service-data-logging&locale=en there's content:
Data and health check logs are valuable for debugging and maintenance purposes. With the data logging feature enabled, IBM Cloud Load Balancer forwards these logs to the IBM Log Analysis with LogDNA External link icon under your account.

But in Chinese version https://cloud.ibm.com/docs/loadbalancer-service?topic=loadbalancer-service-data-logging&locale=zh-CN the content and link points to 
数据和运行状况检查日志对于调试和维护非常有用。启用数据日志记录功能后，IBM Load Balancer 会将这些日志转发到您帐户下的 **[IBM Cloud Log Analysis](https://logging.ng.bluemix.net/?_ga=2.153617915.2128853595.1584505277-747709673.1582675797&cm_mc_uid=48941337196415759551451&cm_mc_sid_50200000=58092021584592957298)** 服务 外部链接图标。
The "IBM Cloud Log Analysis" was deprecated  in Sep. 2019 so the content is not valid now.

**Comment by jbmitch** [comment]
The translation centers are no longer translating Chinese languages, so no more updates for the Chinese languages will be coming in.
